monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "alsa_output.platform-soc_ahub1_mach.stereo-fallback"
      }
    ]
    actions = {
      update-props = {
        priority.session = 1001
      }
    }
  }
]